---
- name: Get list of NetBox devices
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Ensure Netbox script has execute permissions
      command: >
        chmod +x ./scripts/get_netbox_devices.py
      changed_when: false
    
    - name: Run the Python script to retrieve devices
      command: >
        python3 ./scripts/get_netbox_devices.py
        --url {{ netbox_url }}
        --token {{ netbox_token }}
      args:
        chdir: "{{ playbook_dir }}"
      changed_when: false
    
    - name: Load devices from JSON file
      set_fact:
        netbox_devices: "{{ lookup('file', './data/netbox_devices.json') | from_json }}"
    
    - name: Retrieve existing devices from XIQ-SE
      extreme_community.xiqse.xiqse_query:
        query: |
          query {
            network {
              devices {
                ip
              }
            }
          }
        provider:
          host: "{{ xiqse_host }}"
          client_id: "{{ xiqse_client }}"
          client_secret: "{{ xiqse_secret }}"
          verify: "{{ xiqse_verify }}"
      register: result

    - name: Extract existing device
      set_fact:
        existing_devices: "{{ result.result.data.network.devices | map(attribute='ip') | list}}"
    
    - name: Create missing device
      extreme_community.xiqse.xiqse_mutation:
        mutation: |
          mutation {
            network {
              createDevices(input: {
                devices: {
                  ipAddress: "{{ item.mgmt_ip }}"
                  profileName: "{{ item.xiqse_profile }}"
                  siteLocation: "{{ item.path }}"
                }
              }){
                status
              }
            }
          }
        provider:
          host: "{{ xiqse_host }}"
          client_id: "{{ xiqse_client }}"
          client_secret: "{{ xiqse_secret }}"
          verify: "{{ xiqse_verify }}"
      loop: "{{ netbox_devices }}"
      when:
        - item.mgmt_ip is not none
        - item.mgmt_ip not in existing_devices
    
    - name: Compute list of devices to delete
      set_fact:
        devices_to_delete: >-
          {{
            existing_devices
            | difference(netbox_devices | map(attribute='mgmt_ip') | list)
          }}
    
    - name: Delete device
      extreme_community.xiqse.xiqse_mutation:
        mutation: |
          mutation {
            network {
              deleteDevices(input: {
                devices: {
                  ipAddress: "{{ item }}"
                }
              }) {
                status
              }
            }
          }
        provider:
          host: "{{ xiqse_host }}"
          client_id: "{{ xiqse_client }}"
          client_secret: "{{ xiqse_secret }}"
          verify: "{{ xiqse_verify }}"
      loop: "{{ devices_to_delete }}"
    
    - name: Update device
      extreme_community.xiqse.xiqse_mutation:
        mutation: |
          mutation {
            network {
              configureDevice(input: {
                deviceConfig: {
                  ipAddress: "{{ item.mgmt_ip }}"
                  generalConfig: {
                    defaultSitePath: "{{ item.path }}"
                    adminProfile: "{{ item.xiqse_profile }}"
                  }
                }
              }){
                status
              }
            }
          }
        provider:
          host: "{{ xiqse_host }}"
          client_id: "{{ xiqse_client }}"
          client_secret: "{{ xiqse_secret }}"
          verify: "{{ xiqse_verify }}"
      loop: "{{ netbox_devices }}"
      when:
        - item.mgmt_ip is not none