---
- name: Bootstrap - Activer OpenAPI via SSH
  hosts: all
  gather_facts: false
  connection: ansible.netcommon.network_cli

  vars:
    ansible_connection=httpapi
    ansible_network_os=extreme.fe.extreme_fe
    ansible_httpapi_port=9443
    ansible_httpapi_base_path=/rest/openapi
    ansible_httpapi_use_ssl=true
    ansible_httpapi_validate_certs=false
    ansible_user: "rwa"
    ansible_password: "rwa"
    ansible_ssh_common_args: >-
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
      -o KexAlgorithms=+diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1
      -o HostKeyAlgorithms=+ssh-rsa
      -o PubkeyAuthentication=no

  tasks:
    - name: Vérifier si OpenAPI est déjà actif
      extreme.fe.extreme_fe_command:
        commands:
          - show application openapi
      register: openapi_state
      ignore_errors: true

    - name: Confirmer que le port 9443 répond
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 9443
        timeout: 30
      delegate_to: localhost
      vars:
        ansible_connection: local