- name: Debug info Ansible
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Affiche les variables NetBox
      debug:
        msg: "NetBox URL={{ netbox_url }} ; Token={{ netbox_token }}"

- name: Get XIQ-SE version
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Query version
      extreme_community.xiqse.xiqse_version:
        provider:
          host: "{{ xiqse_host }}"
          client_id: "{{ xiqse_client }}"
          client_secret: "{{ xiqse_secret }}"
          verify: "{{ xiqse_verify }}"
      register: result
    - name: Show version
      ansible.builtin.debug:
        msg: "XIQ-SE version: {{ result.version }}"

- name: Get list of NetBox devices
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure Netbox script has execute permissions
      command: >
        chmod +x ./scripts/get_netbox_devices.py
      changed_when: false
    - name: Run the Python script to retrieve devices
      command: >
        python3 ./scripts/get_netbox_devices.py
        --url {{ netbox_url }}
        --token {{ netbox_token }}
      args:
        chdir: "{{ playbook_dir }}"
      changed_when: false