- name: Debug info Ansible
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Affiche les variables NetBox
      debug:
        msg: "NetBox URL={{ netbox_url }} ; Token={{ netbox_token }}"

- name: Get XIQ-SE version
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Query version
      extreme_community.xiqse.xiqse_version:
        provider:
          host: "{{ xiqse_host }}"
          client_id: "{{ xiqse_client }}"
          client_secret: "{{ xiqse_secret }}"
          verify: "{{ xiqse_verify }}"
      register: result
    - name: Show version
      ansible.builtin.debug:
        msg: "XIQ-SE version: {{ result.version }}"

- name: Get list of NetBox devices
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure Netbox script has execute permissions
      command: >
        chmod +x ./scripts/get_netbox_devices.py
      changed_when: false
    - name: Run the Python script to retrieve devices
      command: >
        python3 ./scripts/get_netbox_devices.py
        --url {{ netbox_url }}
        --token {{ netbox_token }}
      args:
        chdir: "{{ playbook_dir }}"
      changed_when: false

- name: Display device names from NetBox inventory
  hosts: all
  gather_facts: false

  tasks:
    - name: Display device hostname
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} - {{ ansible_host | default('N/A') }}"

- name: Check device status in XIQ-SE
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Query device status from XIQ-SE
      extreme_community.xiqse.xiqse_query:
        query: |
          query {
            network {
              device(ip: "{{ hostvars[item].ansible_host }}") {
                down
              }
            }
          }
        provider:
          host: "{{ xiqse_host }}"
          client_id: "{{ xiqse_client }}"
          client_secret: "{{ xiqse_secret }}"
          verify: "{{ xiqse_verify }}"
      register: xiqse_status
      loop: "{{ groups['all'] }}"

    - name: Display device status
      ansible.builtin.debug:
        msg: >-
          {{ item.item }} ({{ hostvars[item.item].ansible_host | default('N/A') }})
          - {{ 'DOWN' if item.data.network.device.down else 'UP' }}
      loop: "{{ xiqse_status.results }}"
      loop_control:
        label: "{{ item.item }}"