- name: Sync XIQ-SE profiles to NetBox custom field
  hosts: localhost
  gather_facts: no
  vars:
    xiqse_verify: false  # ou true selon ton cas
  tasks:

    - name: Query XIQ-SE for profiles
      tchevalleraud.extremenetworks_xiqse.xiqse_query:
        query: |
          query {
            administration {
              profiles {
                profileName
              }
            }
          }
        provider:
          host: "{{ xiqse_host }}"
          client_id: "{{ xiqse_client }}"
          client_secret: "{{ xiqse_secret }}"
          verify: "{{ xiqse_verify }}"
      register: xiqse_profiles_response
    
    - name: Debug
      debug:
        msg: "{{ xiqse_profiles_response }}"

    - name: Patch NetBox custom field with XIQ-SE profiles
      uri:
        url: "{{ netbox_url }}/api/extras/custom-fields/xiqse_profile/"
        method: PATCH
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        body_format: json
        body: >-
          {
            "choices": {
              {% for profile in xiqse_profiles_response.json.data.administration.profiles %}
              "{{ profile.profileName }}": "{{ profile.profileName }}"{% if not loop.last %},{% endif %}
              {% endfor %}
            }
          }
      when: xiqse_profiles_response.json.data.administration.profiles is defined
