- name: Sync XIQ-SE profiles to NetBox custom field
  hosts: localhost
  gather_facts: no
  vars:
    xiqse_verify: false  # ou true selon ton cas
  tasks:

    - name: Query XIQ-SE for profiles
      tchevalleraud.extremenetworks_xiqse.xiqse_query:
        query: |
          query {
            administration {
              profiles {
                profileName
              }
            }
          }
        provider:
          host: "{{ xiqse_host }}"
          client_id: "{{ xiqse_client }}"
          client_secret: "{{ xiqse_secret }}"
          verify: "{{ xiqse_verify }}"
      register: xiqse_profiles_response
    
    - name: Debug
      debug:
        msg: "{{ xiqse_profiles_response}}"

    - name: Set fact for extracted profile names
      set_fact:
        xiqse_profiles: "{{ xiqse_profiles_response.result.data.administration.profiles | map(attribute='profileName') | list }}"

    - name: Get choice sets
      uri:
        url: "{{ netbox_url }}/api/extras/custom-field-choice-sets/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
      register: choice_sets
    
    - name: Debug
      debug:
        msg: "{{ choice_sets }}"
    
    - name: Set fact for xiqse_profiles choice set ID
      set_fact:
        xiqse_profile_choiceset_id: >-
          {{ choice_sets.json.results
            | selectattr('name', 'equalto', 'xiqse_profiles')
            | map(attribute='id') | first }}
    
    - name: Debug
      debug:
        msg: "{{ xiqse_profile_choiceset_id }}"
    
    - name: Set fact with existing profile values in choice set
      set_fact:
        netbox_existing_profiles: >-
          {{ choice_sets.json.results
            | selectattr('name', 'equalto', 'xiqse_profiles')
            | map(attribute='extra_choices') | first
            | map('first') | list }}
    
    - name: Update xiqse_profiles choice set with all profiles (deduplicated)
      uri:
        url: "{{ netbox_url }}/api/extras/custom-field-choice-sets/{{ xiqse_profile_choiceset_id }}/"
        method: PATCH
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        body_format: json
        body: >
          {
            "extra_choices": [
              {% for profile in (netbox_existing_profiles + xiqse_profiles) | unique | sort %}
              ["{{ profile }}", "{{ profile }}"]{% if not loop.last %},{% endif %}
              {% endfor %}
            ]
          }